(() => {
"use strict";
const KEY="one-more-day-v03",$=id=>document.getElementById(id),cap=n=>Math.max(0,Math.min(100,n)),rand=([a,b])=>Math.floor(Math.random()*(b-a+1))+a,cash=n=>`${n<0?"-":""}R${Math.abs(Math.round(n)).toLocaleString("en-ZA")}`;
const jobs=[
 {id:"wash",icon:"🪣",name:"Car washing",desc:"Build a loyal customer base and a wash crew.",energy:-14,pay:[90,140],rep:4,unlock:0,gear:"Pressure washer kit",gearCost:240,titles:["Bucket Runner","Car Washer","Crew Leader","Wash Supervisor","Car Wash Owner"]},
 {id:"move",icon:"📦",name:"Moving service",desc:"Turn heavy lifting into a logistics team.",energy:-20,pay:[135,195],health:-2,social:3,unlock:45,gear:"Moving trolley set",gearCost:320,titles:["Moving Helper","Mover","Team Leader","Move Supervisor","Logistics Owner"]},
 {id:"resell",icon:"📱",name:"Buying & reselling",desc:"Learn the market and grow into a shop.",energy:-10,pay:[100,210],cost:60,knowledge:5,unlock:52,gear:"Market scanner",gearCost:280,titles:["Rookie Trader","Reseller","Deal Scout","Store Manager","Shop Owner"]}
];
const events={
1:{icon:"🚌",tag:"FIRST-DAY PROBLEM",title:"Getting to work",text:"Your first opportunity is across town. How do you get there without ruining your budget or arriving exhausted?",choices:[{text:"Take the minibus taxi",sub:"Cash −R25 • Energy +3",need:25,fx:{cash:-25,energy:3,social:2},result:"You arrive on time and learn two useful names on the way."},{text:"Walk and save",sub:"Energy −8 • Health +3",fx:{energy:-8,health:3,knowledge:2},result:"It is a long walk, but every rand stays in your pocket."}]},
2:{icon:"👟",tag:"WANT vs WEALTH",title:"The fresh-drop temptation",text:"Limited sneakers are calling your name. They cost R180—but that money could keep working.",choices:[{text:"Buy the sneakers",sub:"Happiness +14 • Cash −R180",need:180,fx:{cash:-180,happiness:14},result:"Fresh on your feet. Your wallet needs a lie-down."},{text:"Keep the cash working",sub:"Knowledge +7 • Reputation +2",fx:{knowledge:7,reputation:2,happiness:-3},result:"Future-you sends their regards."}]},
3:{icon:"🏪",tag:"OPPORTUNITY KNOCKS",title:"A tiny business idea",text:"A neighbour selling vetkoek needs R200 for ingredients and a sign. Split tomorrow's profit?",choices:[{text:"Invest R200",sub:"A risky return tomorrow",need:200,fx:{cash:-200,assets:200,invested:1,knowledge:4},result:"Deal done. Now you wait for the lunch rush."},{text:"Pass this time",sub:"Keep your cash",fx:{happiness:-2},result:"You keep your options open."}]},
4:{icon:"😤",tag:"CUSTOMER TROUBLE",title:"A customer is not happy",text:"A customer complains loudly about the service. Other people are watching how you handle it.",choices:[{text:"Fix it for free",sub:"Cash −R60 • Reputation +9",need:60,fx:{cash:-60,reputation:9,social:4},result:"You lose a little money, but gain a customer who now trusts you."},{text:"Stand your ground",sub:"Cash +R20 • Reputation −6",fx:{cash:20,reputation:-6,happiness:-2},result:"You keep today's money, but the story travels faster than you expected."}]},
5:{icon:"📱",tag:"CHAOS EVENT",title:"Hey! That's my phone!",text:"Someone snatches your phone at the taxi rank. Your health and energy affect the chase.",choices:[{text:"Give chase!",sub:"Uses health, energy and luck",chase:1},{text:"Let it go",sub:"Stay safe • Cash −R150",fx:{cash:-150,happiness:-8},result:"It hurts, but no phone is worth your life."}]},
6:{icon:"🤝",tag:"SOCIAL CAPITAL",title:"A friend needs a favour",text:"Lerato needs interview help. It costs your evening, but people remember who showed up.",choices:[{text:"Help prepare",sub:"Energy −10 • Social +10 • Reputation +5",fx:{energy:-10,social:10,reputation:5,happiness:3},result:"Lerato walks in confident. That's another kind of profit."},{text:"Focus on yourself",sub:"Energy +4 • Social −5",fx:{energy:4,social:-5},result:"You protect your time. Lerato understands—mostly."}]},
7:{icon:"🎉",tag:"WEEK-END DECISION",title:"How do you celebrate?",text:"You survived your first working week. Your friends invite you out, but tomorrow's ambitions are already calling.",choices:[{text:"Celebrate with everyone",sub:"Cash −R100 • Social +10 • Happiness +12",need:100,fx:{cash:-100,social:10,happiness:12},result:"Money comes and goes. Tonight becomes a memory worth keeping."},{text:"Plan the next move",sub:"Knowledge +8 • Energy +5",fx:{knowledge:8,energy:5,happiness:-2},result:"You sketch the next stage of your career while the city settles down."}]}
};
let s,timer;
const fresh=(name="Thando")=>({name:name.trim()||"Thando",day:1,age:18,cash:250,startCash:250,health:76,energy:82,knowledge:42,social:55,happiness:68,reputation:35,assets:0,debt:0,job:null,careerHistory:[],xp:0,equipment:false,workers:0,worked:false,eventDone:false,invested:false,jobsDone:0});
const save=()=>localStorage.setItem(KEY,JSON.stringify(s));const load=()=>{try{let data=JSON.parse(localStorage.getItem(KEY));if(data&&!Array.isArray(data.careerHistory))data.careerHistory=data.job?[data.job]:[];return data}catch{return null}};const worth=()=>s.cash+s.assets-s.debt;const rank=()=>s.xp>=14?4:s.xp>=9?3:s.xp>=5?2:s.xp>=2?1:0;
function fx(x={}){["cash","assets","debt"].forEach(k=>s[k]+=Number(x[k]||0));["health","energy","knowledge","social","happiness","reputation"].forEach(k=>s[k]=cap(s[k]+Number(x[k]||0)));if(x.invested)s.invested=true}
function toast(x){$("toast").textContent=x;$("toast").classList.add("show");clearTimeout(timer);timer=setTimeout(()=>$("toast").classList.remove("show"),3000)}
function stat(k,n,i){return `<div class="stat"><div class="stat-label"><span>${i} ${n}</span><b>${Math.round(s[k])}</b></div><div class="bar"><i style="width:${s[k]}%"></i></div></div>`}
function render(){
 $("dayValue").textContent=`${s.day} / 7`;$("ageValue").textContent=s.age;$("cashValue").textContent=cash(s.cash);$("netWorthValue").textContent=cash(worth());$("statGrid").innerHTML=stat("health","Health","♥")+stat("energy","Energy","⚡")+stat("knowledge","Know.","◆")+stat("social","Social","●")+stat("happiness","Happy","☀")+stat("reputation","Rep.","★");story();career();save();
}
function story(){const e=events[s.day];if(e&&!s.eventDone){$("storyIcon").textContent=e.icon;$("storyKicker").textContent=e.tag;$("storyTitle").textContent=e.title;$("storyText").textContent=e.text;$("choiceList").innerHTML=e.choices.map((c,i)=>`<button class="choice" data-choice="${i}" ${c.need>s.cash?"disabled":""}>${c.text}<small>${c.need>s.cash?`Need ${cash(c.need)}`:c.sub}</small></button>`).join("");return}$("storyIcon").textContent=s.worked?"✅":"🌅";$("storyKicker").textContent=`DAY ${s.day}`;$("storyTitle").textContent=s.job?"Today's work is done.":`Choose your path, ${s.name}.`;$("storyText").textContent=s.job?"Your career runs automatically each day. Invest in it below or move on when ready.":"Choose a starting career once. After that, work happens automatically while you make the bigger decisions.";$("choiceList").innerHTML=""}
function career(){
 if(!s.job){$("workTitle").textContent="Choose a career path";$("hustleList").innerHTML=jobs.map(j=>{let open=j.unlock===0||s.knowledge>=j.unlock||s.reputation>=j.unlock;return `<button class="hustle" data-job="${j.id}" ${open?"":"disabled"}><span class="hustle-icon">${j.icon}</span><span><strong>${j.name}</strong><small>${open?j.desc:`Unlock at ${j.unlock} knowledge or reputation`}</small></span><span class="reward">${open?`${cash(j.pay[0])}+`:"🔒"}</span></button>`}).join("")}
 else{let j=jobs.find(x=>x.id===s.job),r=rank(),next=[2,5,9,14,20][r],wc=350+s.workers*300,available=jobs.find(x=>!s.careerHistory.includes(x.id)&&(s.knowledge>=x.unlock||s.reputation>=x.unlock));$("workTitle").textContent=j.titles[r];$("hustleList").innerHTML=`<div class="career-card"><div class="career-top"><span class="hustle-icon">${j.icon}</span><div><strong>${j.titles[r]}</strong><small>${j.name} • Automatic daily work</small></div><span class="reward">~${cash(estimate(j))}/day</span></div><div class="career-progress"><i style="width:${Math.min(100,s.xp/next*100)}%"></i></div><div class="career-meta"><span>${s.xp} experience</span><span>${r<4?`${next-s.xp} to promotion`:"Top rank"}</span></div><div class="upgrade-list"><button class="upgrade" data-up="equipment" ${s.cash<j.gearCost||s.equipment?"disabled":""}><strong>🧰 ${s.equipment?"Equipment owned":j.gear}</strong><small>${s.equipment?"Permanent +35% job income":`${cash(j.gearCost)} • Buy once • +35%`}</small></button><button class="upgrade" data-up="worker" ${s.cash<wc||r<2?"disabled":""}><strong>👥 Hire a worker</strong><small>${r<2?"Unlock after promotion":`${cash(wc)} • +R55 daily`}</small></button></div>${available?`<button class="opportunity" data-switch="${available.id}">✨ New opportunity awarded: ${available.name}</button>`:""}</div>`}
 let ready=!!s.job&&s.worked;$("nextDayButton").disabled=!ready||!!(events[s.day]&&!s.eventDone);$("nextDayButton").textContent=ready?(s.day===7?"SEE WEEK 1 SUMMARY →":"NEXT DAY →"):"CHOOSE A CAREER FIRST";
}
function estimate(j){return Math.round((j.pay[0]+j.pay[1])/2*(s.equipment?1.35:1)+s.workers*55)}
function work(first=false){let j=jobs.find(x=>x.id===s.job),old=rank(),earned=Math.round(rand(j.pay)*(s.equipment?1.35:1)+s.workers*55);fx({cash:earned-(j.cost||0),energy:j.energy,health:j.health||0,knowledge:j.knowledge||0,social:j.social||0,reputation:j.rep||0,happiness:2});s.xp++;s.jobsDone++;s.worked=true;let promoted=rank()>old;if(promoted){let bonus=rank()*100;s.cash+=bonus;s.reputation=cap(s.reputation+4);if(!first)toast(`🎉 Promoted to ${j.titles[rank()]}! ${cash(bonus)} milestone bonus.`)}else if(!first)toast(`${j.icon} Automatic work completed: +${cash(earned)}.`)}
function chooseJob(id){if(s.job)return;s.job=id;s.careerHistory=[id];work(true);toast(`Career started. ${jobs.find(x=>x.id===id).name} will now happen automatically.`);render()}
function upgrade(type){if(type==="equipment"){let j=jobs.find(x=>x.id===s.job);if(s.cash<j.gearCost||s.equipment)return;s.cash-=j.gearCost;s.assets+=Math.round(j.gearCost*.65);s.equipment=true;toast(`🧰 ${j.gear} purchased. This career permanently earns 35% more.`)}else{let c=350+s.workers*300;if(s.cash<c||rank()<2)return;s.cash-=c;s.workers++;toast("👥 Worker hired. Your team earns extra income every day.")}render()}
function switchJob(id){if(s.careerHistory.includes(id))return;s.job=id;s.careerHistory.push(id);s.xp=0;s.equipment=false;s.workers=0;toast(`✨ New career started: ${jobs.find(x=>x.id===id).name}. Your previous career is now part of your history.`);render()}
function choose(i){let c=events[s.day].choices[i];if(c.need>s.cash)return;if(c.chase){let won=Math.random()<.25+(s.health+s.energy)/300;fx(won?{energy:-18,health:-5,reputation:7,happiness:8}:{energy:-20,health:-8,cash:-150,happiness:-8});c.result=won?"You catch them and recover your phone. Main-character energy!":"You lose them in the crowd. Bruised pride, but you're safe."}else fx(c.fx);s.eventDone=true;toast(c.result);render()}
function next(){if(!s.worked||events[s.day]&&!s.eventDone)return;if(s.day===7)return summary();s.day++;s.worked=false;s.eventDone=!events[s.day];fx({energy:26,health:3,happiness:-1});if(s.day===4&&s.invested){let p=rand([40,180]);s.cash+=200+p;s.assets-=200;toast(`🏪 Business return: your R200 plus ${cash(p)} profit!`)}work();render();window.scrollTo({top:0,behavior:"smooth"})}
function summary(){$("gameScreen").classList.add("hidden");$("summaryScreen").classList.remove("hidden");$("resetButton").classList.add("hidden");let gain=worth()-s.startCash,score=Math.max(0,Math.round(worth()+s.knowledge*3+s.reputation*3+s.happiness*2)),j=jobs.find(x=>x.id===s.job);$("summaryTitle").textContent=`You made it, ${s.name}.`;$("summaryMessage").textContent="Your first week built more than cash—it started a career.";$("summaryScore").innerHTML=`${score}<small>LIFE SCORE</small>`;$("summaryGrid").innerHTML=`<div class="summary-item"><span>CAREER</span><strong>${j.titles[rank()]}</strong></div><div class="summary-item"><span>NET WORTH</span><strong>${cash(worth())}</strong></div><div class="summary-item"><span>WEEK'S GROWTH</span><strong class="${gain>=0?"positive":"negative"}">${gain>=0?"+":""}${cash(gain)}</strong></div><div class="summary-item"><span>TEAM SIZE</span><strong>${s.workers+1}</strong></div>`;$("summaryQuote").textContent="A job pays for today. A system can pay for tomorrow."}
function show(){ $("startScreen").classList.add("hidden");$("summaryScreen").classList.add("hidden");$("gameScreen").classList.remove("hidden");$("resetButton").classList.remove("hidden");render() }
function reset(){if(confirm("Start over? Your current week will be replaced.")){localStorage.removeItem(KEY);location.reload()}}
$("newLifeForm").addEventListener("submit",e=>{e.preventDefault();s=fresh($("playerName").value);show()});$("continueButton").addEventListener("click",()=>{s=load();show()});$("resetButton").addEventListener("click",reset);$("replayButton").addEventListener("click",()=>{localStorage.removeItem(KEY);s=fresh();show()});$("nextDayButton").addEventListener("click",next);$("hustleList").addEventListener("click",e=>{let j=e.target.closest("[data-job]"),u=e.target.closest("[data-up]"),n=e.target.closest("[data-switch]");if(j)chooseJob(j.dataset.job);if(u)upgrade(u.dataset.up);if(n)switchJob(n.dataset.switch)});$("choiceList").addEventListener("click",e=>{let b=e.target.closest("[data-choice]");if(b)choose(Number(b.dataset.choice))});
let saved=load();$("continueButton").classList.toggle("hidden",!saved);if(saved)$("continueButton").textContent=`Continue ${saved.name}'s career • Day ${saved.day}`;
})();
